### ISSUE TITLE
Alertmanager api 404 errors

### ISSUE THREAD

**Issue by aaron7** [weaveworks/cortex#529]
We are seeing 404 errors for some of the requests the ruler is making to the alertmanager.

ruler logs: 
`
time="2017-08-03T13:17:38Z" level=error msg="Error sending alerts: bad response status 404 Not Found" alertmanager="http://3138343130383837.alertmanager.cortex.svc.cluster.local:80/api/prom/alertmanager/api/v1/alerts" count=48 source="notifier.go:370
`

alertmanager logs: 
`
time="2017-08-03T13:17:08Z" level=warning msg="POST /api/prom/alertmanager/api/v1/alerts (404) 169.984µs"
`

**Comment by aaron7** [comment]
@jml suggested that this issue could be related to users who have alerts defined but have no valid alertmanager config.

**Comment by bboreham** [comment]
Some other ideas (originally on #545):
 * implement a sink for webhooks inside the alertmanager process, so they are silently ignored
 * add a 'null' receiver to prometheus alertmanager
 * have the ruler examine the route config, so it can tell it's invalid
 * have the multitenant alertmanager return 204 instead of 404 when it doesn't have a config (from @aaron7 )

**Comment by bboreham** [comment]
Fixed by #529

**Comment by shaarmaayushh** [comment]
i am still having this same issue 
ts=2025-08-27T08:25:30.409100501Z caller=notifier.go:544 level=error user=fake alertmanager=http://cortex-mon-cluster-alertmanager:8080/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"

can someone tell me how to resolve this man
